### ISSUE TITLE
can i use this

### ISSUE THREAD

**Issue by phobologicalt** [moomooooo/Moo-Base#2]
i wanna make a private client and was wondering if I could use this? im too lazy to actually set up a custom base, also i can slide you the private client if you want, salutations ~ phobo

**Comment by phobologicalt** [comment]
also its been a while, are you ever gonna finish this base?

**Comment by srgantmoomoo** [comment]
Yes u can use this, https://github.com/moomooooo/Moo-Base/blob/main/LICENSE. Also, I don’t plan on working on it anytime soon, I’m pretty busy with other things.
